# debug postgres connection: https://dev.to/renanbr/controlling-service-readiness-in-docker-compose-4dfm
# https://docs.docker.com/compose/startup-order/

version: '3.7'

services:
  it-job-search-engine:
    container_name: it-job-search-engine
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
#    env_file:
#      - .env
    environment:
      SERVER_PORT: 4000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: it-job-search-engine
      SECRET: thisIsASecretKey
      MIGRATIONS_DIR: src/migrations
    networks:
      - webnet
    depends_on:
      - db
    command: npm run start:dev
  db: # hostname inside network
    container_name: it-job-search-engine-db
    image: postgres:12
    restart: always
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: it-job-search-engine
#    expose:
#      - 5432
#    ports:
#      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:
volumes:
  pgdata:
